### ISSUE TITLE
Using arenas to replace allocation trickery

### ISSUE THREAD

**Issue by jzelinskie** [outcaste-io/ristretto#9]
Behind a flag, [this proposal](https://github.com/golang/go/issues/51317) for memory arenas has landed in Go.
It's quite possible that leveraging this could eliminate a lot of the low-level nastiness in the z package.

I haven't done a deep dive, but it seems like it could be an improvement.

**Comment by manishrjain** [comment]
Are you talking about the use of jemalloc in z package? We have been using memory arenas since 2017 in Badger [1], so the memory arena isn't a new thing. The benefit of jemalloc is to be able to allocate many small objects and release them independently of each other. A memory arena wouldn't help with that.

In fact, even with arenas, we've seen that jemalloc does a better job of releasing memory than Go does. Let me know if you meant something else.

[1]: https://github.com/outcaste-io/badger/blob/main/skl/arena.go

**Comment by manishrjain** [comment]
Closing this issue. Feel free to re-open if needed.
